aldrichdev/neatf2p-nextjs

babel.config.js, package-lock.json, package.json, src/components/atoms/NewsAndUpdates/NewsAndUpdates.tsx, src/components/atoms/OnlinePlayers/OnlinePlayers.tsx, src/lib/db.ts, src/lib/helpers/base64.ts, src/lib/helpers/date/date.test.ts, src/lib/helpers/date/date.ts, src/lib/helpers/string/stringUtils.ts, src/pages/admin/newsPostForm/NewsPostForm.styled.ts, src/pages/admin/newsPostForm/index.tsx, src/pages/api/getNewsPosts/index.ts, src/pages/api/getOnlinePlayerCount/index.ts, src/pages/api/submitNewsPost/index.ts, src/pages/upload/index.tsx, src/sql/getOnlinePlayers.sql, src/sql/insertImage.sql, src/sql/insertNewsPost.sql
- Added `admin/NewsPostForm` (unauthenticated for now)
- Miscellaneous changes
- Added check in `OnlinePlayers` component to prevent it from rendering with no data
- Removed unnecessary `values: []` parameter in query code
- Added date helpers and tests
- Fixed some TypeScript errors and warnings
=> F2P-2 | Build News Post Submission Form

src/pages/_app.styled.ts, src/pages/_app.tsx
- Added link to homepage on site banner
=> F2P-33 | Clicking the banner should take the user to the homepage

package-lock.json, src/components/atoms/OnlinePlayers/OnlinePlayers.styled.ts, src/components/molecules/MainNavigation/MainNavigation.styled.ts, src/components/molecules/MainNavigation/MainNavigation.tsx, src/components/molecules/MainNavigation/index.ts, src/pages/_app.tsx, src/pages/about/index.styled.ts, src/pages/about/index.tsx, src/pages/bug-reports/index.tsx, src/pages/discord/index.tsx, src/pages/hiscores/index.tsx, src/pages/how-to-play/index.tsx, src/pages/index.tsx, tsconfig.json
- Added a main navigation (`MainNavigation`), which contains a Discord link
- Created several pages, mostly filler content for now
- Increased players online text on mobile to 20px, centered
- Changed homepage verbiage
=> F2P-10 | Add Discord link to Homepage

package-lock.json, package.json, src/components/atoms/NewsAndUpdates/NewsAndUpdates.tsx, src/pages/admin/newsPostForm/index.tsx
- Enabled links and other HTML in news post descriptions / body
- Added field info helper for `Body` field of `newsPostForm` indicating HTML is allowed
=> F2P-45 | Can news post descriptions support links?

src/components/atoms/NewsPostDetailItem/NewsPostDetailItem.styled.ts, src/components/molecules/NewsPostListItem/NewsPostListItem.styled.ts
- Fixed news post styling issues around images on detail page and tablet results view
=> F2P-53 | Fix styling around news post images

src/components/molecules/AccountWidget/AccountWidget.tsx, src/helpers/window.ts, src/pages/account/create/index.tsx, src/pages/account/login/index.tsx
- Created `redirectTo` helper and reused it for any `win.location` references
=> F2P-50 | Create a redirectTo helper 

README.md
- Added Node req version and troubleshooting of this error to the readme
=> F2P-54 | npm run build causes a memory issue

src/pages/account/login/index.tsx, src/pages/api/updateLastLogin/index.ts
- Set `lastModified` of `users` when setting `lastLogin` (eventually we will need to do this for other user update queries like password or email changes)
=> F2P-20 | SPIKE: Find a way to associate web accounts with game accounts

.eslintrc.json, package.json
- Fixed `eslint` config so that unused imports show as a problem in VS Code and are underlined in red
- Added `eslint` command to `dev` script so those issues are found when local is started
=> F2P-59 | Add eslint rule to project so unused imports show up as errors in IDE

src/pages/account/game-accounts/create/index.tsx
- Fixed issues with game account names allowing spaces, symbols, bad words
- Replaced underscores with spaces for game account creation
- Fixed issue with duplicate game accounts being created due to casing differences
- Fixed issue with the website not finding existing account names due to casing differences
=> F2P-65 | Game account creation needs more validation

src/pages/account/game-accounts/create/index.tsx
- Fixed issue with game account creation Submit button being allowed to be pressed multiple times and create multiple accounts at once
=> F2P-67 | Create Account form needs button disabled after form is submitted

src/pages/how-to-play/index.tsx
- Updated How to Play page body to mention alpha testing phase
=> F2P-77 | Update How to Play page temporarily with alpha testing info

src/components/organisms/GameAccountsTable/GameAccountsTable.tsx, src/components/organisms/GameAccountsTable/GameAccountsTable.types.ts, src/components/organisms/GameAccountsTableMobile/GameAccountsTableMobile.tsx, src/components/organisms/GameAccountsTableMobile/GameAccountsTableMobile.types.ts, src/hooks/useGameAccounts.ts, src/pages/account/game-accounts/index.tsx
- Reused duplicate code between `GameAccountsTable` and `GameAccountsTableMobile`
=> F2P-62 | Refactor GameAccountTable and GameAccountRow components to share code between Mobile version and default

pull_request_template.md, src/helpers/date/date.ts
- Fixed issues with non-military times being negative and midnight times being 0
- Added basic PR template
=> Time display issues

src/components/molecules/ReadMore/ReadMore.tsx
- Fixed issue with ellipsis being on its own line
- Tweaked Read More text
=> F2P-84 | Ellipsis should probably not show on a new line

src/pages/index.tsx, src/styledPages/Homepage.styled.ts
- Added teaser video to homepage
=> F2P-93 | Should we put the teaser video on the homepage?

package-lock.json, package.json, src/pages/admin/newsPostForm/index.tsx, src/styledPages/NewsPostForm.styled.ts
- Updated news post form to support markdown
=> F2P-90 | The NewsPostForm should ideally allow markdown

src/components/organisms/NewsPostListItem/NewsPostListItem.styled.ts, src/components/organisms/NewsPostListItem/NewsPostListItem.tsx
- Improved appearance of news post images on mobile, made placeholder news post image round
=> F2P-89 | News post images on mobile are huge and look kind of bad

src/data/BannedText.ts, src/pages/account/change-email/[id].tsx, src/pages/account/change-email/index.tsx, src/pages/account/change-email/success/index.tsx, src/pages/account/change-password/index.tsx, src/pages/account/change-password/success/index.tsx, src/pages/account/change-username/index.tsx, src/pages/account/change-username/success/index.tsx, src/pages/account/game-accounts/create/index.tsx, src/pages/account/index.tsx, src/pages/api/ironLogin/index.ts, src/pages/api/updateWebsiteUserEmailAddress/index.ts, src/pages/api/updateWebsiteUserUsername/index.ts, src/styledPages/Account.styled.ts
- Added Change Email, Change Username and Change Password functionality
- Fixed a bug in `ironLogin` where email was not set correctly in session
- Created `BannedText` file and updated bad word list
=> F2P-55 | Logged-in users can change their website account email, username or password

src/components/organisms/NewsPostListItem/NewsPostListItem.styled.ts, src/components/organisms/NewsPostListItem/NewsPostListItem.tsx
- Fixed paragraph spacing issue with news posts that have exterior p tags due to new news post form logic
=> F2P-102 | New news post form has exterior p tags

src/components/atoms/HiscoresMenu/HiscoresMenu.tsx, src/globalTypes/Hiscores/HiscoreType.ts, src/pages/api/getPlayerHiscore/index.ts, src/pages/api/queryHiscores/index.ts, src/pages/hiscores/player/[accountName].tsx
- Removed Attack, Defense and Strength info from Hiscores (due to a recent poll)
=> F2P-115 | Update Hiscores based on community poll

src/pages/bug-reports/index.tsx, src/styledPages/ReportABug.styled.ts
- Added green issues link to bug report success message
- Reused repo owner value
=> F2P-107 | Add a link to the bug report creation success message

src/helpers/api/apiUtils.ts, src/pages/account/login/forgot-password/index.tsx, src/pages/account/login/index.tsx, src/pages/api/getUser/index.ts
- Changed website account sign ins to require email only instead of email or username (this was done for security purposes, as usernames are easily guessable and this reveals website account passwords which can be cracked), potentially fixed issue with logout sometimes taking 2 tries (probably not)
=> Sign in change & potential logout bug fix

src/helpers/api/apiUtils.ts
- Updated `shouldBlockApiCall` so it cannot return undefined if an error occurs
- Added catch block to log the error and block the call
=> F2P-124 | `shouldBlockApiCall` fix

src/pages/account/create/index.tsx, src/pages/account/create/success/index.tsx
- Added logic in account creation process to log the user's IP when they login automatically after clicking Submit
- Added bold styling to website account name on creation success page
Created a new account locally and my IP is logged in the database after it is created.
=> F2P-141 | Log user's IP on account creation

src/components/molecules/AlreadyLoggedIn/AlreadyLoggedIn.tsx, src/components/molecules/MustBeAdminBlock/MustBeAdminBlock.tsx, src/components/molecules/NotLoggedIn/NotLoggedIn.tsx, src/pages/about/index.tsx, src/pages/account/change-email/[id].tsx, src/pages/account/change-email/success/index.tsx, src/pages/account/change-password/index.tsx, src/pages/account/change-password/success/index.tsx, src/pages/account/change-username/index.tsx, src/pages/account/change-username/success/index.tsx, src/pages/account/create/index.tsx, src/pages/account/create/success/index.tsx, src/pages/account/game-accounts/create/index.tsx, src/pages/account/game-accounts/create/success/index.tsx, src/pages/account/game-accounts/index.tsx, src/pages/account/index.tsx, src/pages/account/login/forgot-password/index.tsx, src/pages/account/login/forgot-password/success/index.tsx, src/pages/account/login/index.tsx, src/pages/account/reset-password/[resetToken].tsx, src/pages/account/reset-password/success/index.tsx, src/pages/admin/newsPostForm/index.tsx, src/pages/bug-reports/index.tsx, src/pages/hiscores/index.tsx, src/pages/hiscores/player/[accountName].tsx, src/pages/how-to-play/index.tsx, src/pages/how-to-play/rscplus/index.tsx, src/pages/news/index.tsx, src/pages/news/post/[id]/index.tsx, src/pages/webclient/index.tsx
- Added custom browser titles to all pages for better SEO, link sharing, and tab context
Loaded all pages and saw the new browser titles are showing.
=> F2P-146 | Browser title is the same for all pages

src/components/molecules/RulesAcceptanceCheckbox/RulesAcceptanceCheckbox.styled.ts, src/components/molecules/RulesAcceptanceCheckbox/RulesAcceptanceCheckbox.tsx, src/components/molecules/RulesAcceptanceCheckbox/RulesAcceptanceCheckbox.types.ts, src/components/molecules/RulesAcceptanceCheckbox/index.ts, src/pages/about/rules/index.tsx, src/pages/account/create/index.tsx, src/pages/account/game-accounts/create/index.tsx, src/styledPages/Rules.styled.ts
- Added rules page
- Added required rules acceptance checkboxes to account creation forms
=> F2P-156 | Need to show rules on website

src/globalTypes/Database/HiscoreDataRow.ts, src/pages/api/getPlayerHiscore/index.ts, src/pages/hiscores/player/[accountName].tsx
- Added last login date to player hiscore pages
- Login dates load, seem accurate and look good.
=> F2P-167 | Add last login date to player hiscores

src/pages/account/create/index.tsx, src/pages/account/game-accounts/create/index.tsx
- Fixed console warnings regarding autocomplete attribute
- Confirmed warning no longer appears in console on Register and Create Game Account pages
=> F2P-128 | 'Input elements should have autocomplete' warning

src/pages/account/change-email/index.tsx
- Fixed issue with change email feature allowing users to change to an email that is in use by another user account
=> F2P-158 | Error trying to change email if it already is taken

src/components/MainNavigationDropdownItem/MainNavigationDropdownItem.styled.ts, src/components/atoms/MainNavigation/MainNavigation.tsx, src/components/molecules/CommunityAchievementsTable/CommunityAchievements.data.ts, src/components/molecules/CommunityAchievementsTable/CommunityAchievementsTable.styled.ts, src/components/molecules/CommunityAchievementsTable/CommunityAchievementsTable.tsx, src/components/molecules/CommunityAchievementsTable/index.ts, src/helpers/renderUtils.tsx, src/pages/about/rules/index.tsx, src/pages/hall-of-fame/index.tsx
- Added Hall of Fame page and Community Achievements table
- Decreased nav sub-link font size
- Updated NPC Hiscores nav link title
Confirmed Hall of Fame page looks good on mobile, tablet and desktop.
=> F2P-150 | Make a community history page?

src/hooks/usePasswordHashing.ts, src/pages/account/change-email/[id].tsx, src/pages/account/login/index.tsx
- Updated email change logic to send email to old address when website email is changed
Confirmed an email is sent to the old email address when a website user's email is changed, and the template variable works (and shows the new address).
=> F2P-139 | Potential issue with `updateWebsiteUserEmailAddress`

src/pages/api/submitNewsPost/index.ts
- Fixed issue with news post API handler where it created image record even if no image was uploaded
- Creating a news post without an image via the form does NOT create an image record in the `images` table, and the news post record's `image` value is `(NULL)`
- Creating a news post *with* an image DOES create the image and link it to the news post.
=> F2P-127 | Why does the news post form create an image record if no image is uploaded?

src/components/molecules/CommunityAchievementsTable/CommunityAchievements.data.ts
- Added info for first to full adamantite
=> F2P-190 | Update HOF page

src/components/molecules/CommunityAchievementsTable/CommunityAchievements.data.ts, src/pages/about/index.tsx, src/pages/hiscores/player/[accountName].tsx, src/pages/how-to-play/index.tsx, src/styledPages/HowToPlay.styled.ts
- Fixed Last Login '1969' bug for accounts that never logged in
- Updated Hall of Fame page to include sir prysin (99 Hits)
- Made various content updates to the website for clarity
=> F2P-187 | Various fixes

src/components/molecules/CharacterInfoModal/CharacterInfoModal.tsx, src/helpers/numberUtils.ts, src/helpers/string/stringUtils.ts, src/pages/api/getKdrStatisticsForPlayer/index.ts
- Updated KDR logic to call a new stored procedure that returns kills, deaths and KDRs
- Updated KDRs to account for the player's former name
=> F2P-197 | PKDR may be off for renamed accounts

README.md, package-lock.json, package.json, src/pages/webclientV2/index.tsx
- Updated `@types/node` version to 22
- Updated Node version listed in readme
- Added note to `webclientV2` page
=> F2P-217 | Upgrade Node.js

src/pages/hiscores/player/[accountName].tsx, src/pages/npc-hiscores/player/[accountName].tsx
- Halved revalidate time for player hiscores pages
=> Halve Revalidate for Player Hiscores
