aldrichdev/neatf2p-nextjs

- src/components/atoms/NewsAndUpdates/NewsAndUpdates.tsx
- src/lib/helpers/date/date.ts
- src/pages/admin/newsPostForm/index.tsx
- Changed `NewsPostForm` to submit current date as ISO string
- Updated `NewsAndUpdates` component to print date in the string format we were inserting it
- Sorted news posts so most recent ones appear at the top
- Added time to date strings (so time now appears on the website)
- While testing this, I deleted all newspost records (and their associated images) that had the wrong date format.
- The time shown in the Latest News module seems to work regardless of the user's timezone.
> F2P-34 | Sort news posts by `datePosted` DESC

- src/components/atoms/NewsAndUpdates/NewsAndUpdates.styled.ts
- Fixed issue with news post text breaking to a new line on tablet & desktop if too long
> F2P-36 | Long news posts don't appear correctly

- src/components/atoms/NewsAndUpdates/NewsAndUpdates.styled.ts
- src/components/atoms/NewsAndUpdates/NewsAndUpdates.tsx
- src/components/molecules/MainNavigation/MainNavigation.tsx
- src/pages/api/getNewsPosts/index.ts
- src/pages/index.tsx
- src/pages/news/index.tsx
- Added News page
- Added read more link to `NewsAndUpdates` via prop
- Added limit parameter to `getNewsPosts` API call
- Made heading of `NewsAndUpdates` configurable via prop
- Tweaked spacing below `NewsAndUpdates` heading
> F2P-40 | Latest News section should probably only show X posts and then a read more link

- src/components/atoms/OnlinePlayers/OnlinePlayers.tsx
- src/components/molecules/Spinner/Spinner.tsx
- src/components/molecules/Spinner/index.ts
- src/components/organisms/NewsAndUpdates/NewsAndUpdates.tsx
- src/pages/news/post/[id]/index.tsx
- Added loading spinner for database-result components
- Reduced unnecessary `useEffect` calls
> F2P-46 | Database-dependent components do not appear until 3-4 seconds after page load

- package.json
- src/helpers/date/date.ts
- Added timezone abbreviations to news post dates
- Removed unused npm script `test`
> F2P-52 | Add timezone to news post dates

- src/helpers/apiHandler.ts
- src/pages/account/game-accounts/create/index.tsx
- src/pages/api/createCurstatsRecord/index.ts
- src/pages/api/createGameAccount/index.ts
- src/pages/api/updateGameAccountPassword/index.ts
- src/pages/api/updateLastLogin/index.ts
- src/pages/api/updateWebsiteUserPassword/index.ts
- Fixed game account creation so that a `curstats` record is created after the player record is, therefore fixing an issue with new accounts created through the website not being able to complete the tutorial.
- Renamed `handleUpdate` to `handleManipulate`
> F2P-61 | New accounts created via the website cannot get past the customization screen

- src/components/molecules/AccountWidget/AccountWidget.styled.ts
- src/components/molecules/AlreadyLoggedIn/AlreadyLoggedIn.tsx
- src/components/molecules/NotLoggedIn/NotLoggedIn.tsx
- src/hooks/useAuthentication.ts
- src/pages/account/create/index.tsx
- src/pages/account/create/success/index.tsx
- src/pages/account/game-accounts/create/index.tsx
- src/pages/account/game-accounts/create/success/index.tsx
- src/pages/account/game-accounts/index.tsx
- src/pages/account/index.tsx
- src/pages/account/login/forgot-password/index.tsx
- src/pages/account/login/index.tsx
- src/pages/account/reset-password/success/index.tsx
- src/pages/admin/newsPostForm/index.tsx
- Added loading spinner to all pages that call `useAuthentication` and return different JSX based on the user returned from this hook. This prevents pages from showing the wrong information for a split second because the user has not been fetched from the API yet.
- Refactored `AlreadyLoggedIn` to accept a custom message
- Updated the create page to use `AlreadyLoggedIn`
- Fixed an account widget link styling issue on mobile
- Tweaked the `NotLoggedIn` component message
- Made the Forgot Password block left-aligned
- Fixed problem with error state not appearing on `/account/game-accounts/create/success` page
> F2P-60 | Handle page loads better so that "Access Denied" block doesn't show for a split second

- src/components/organisms/PasswordModal/PasswordModal.tsx
- src/helpers/string/stringUtils.ts
- src/pages/account/game-accounts/create/index.tsx
- Added new validation for game account passwords so they cannot contain spaces or any special characters except underscores
> F2P-68 | Passwords cannot have special characters, but should be able to (Temporary fix)

- .fttemplates/Component/[FTName].styled.ts
- .fttemplates/Component/[FTName].tsx
- .fttemplates/Component/[FTName].types.ts
- .fttemplates/Component/index.ts
- .prettierignore
- src/components/molecules/MustBeAdminBlock/MustBeAdminBlock.tsx
- src/components/molecules/MustBeAdminBlock/index.ts
- src/pages/admin/newsPostForm/index.tsx
- src/pages/admin/upload/index.tsx
- Fixed upload page by moving it to `admin/` and locking access down to admins. **Notes**:
- This page does NOT upload images to the database, it only uploads them to the page
- This page is still useful because it logs an image's base 64 string when you upload it, which is useful for creating new `image` table records
- Reused admin message by creating `MustBeAdminBlock` component
- Added `.fttemplates` config so creating new components is easier
- Added `.fttemplates` files to Prettier ignore as they are not supposed to be syntactically valid
> Upload Page Fix, `MustBeAdminBlock`, Folder Templates Config

- src/components/atoms/HiscoresTable/HiscoresTable.styled.ts
- src/components/atoms/PlayerHiscoreTable/PlayerHiscoreTable.styled.ts
- src/components/atoms/PlayerHiscoreTable/PlayerHiscoreTable.tsx
- src/components/molecules/Spinner/Spinner.tsx
- src/pages/hiscores/player/[accountName].tsx
- Player lookup now performs a case-insensitive search
- Fixed an issue with the spinner and one of the tables (skills menu or hiscores table) appearing on the same line on mobile when the hiscores are still loading
- Fixed a minor UI glitch with player hiscore table cells not being the same width on mobile
> F2P-98 | Hiscores tweaks

- src/components/organisms/NewsPostListItem/NewsPostListItem.styled.ts
- src/components/organisms/NewsPostListItem/NewsPostListItem.tsx
- Made news post list item images clickable, to the new posts page
> F2P-86 | Clicking on a news post image should open the news post

- src/components/atoms/HiscoresTable/HiscoresTable.styled.ts
- src/components/atoms/HiscoresTable/HiscoresTable.tsx
- src/components/atoms/PlayerHiscoreTable/PlayerHiscoreTable.styled.ts
- src/components/atoms/PlayerHiscoreTable/PlayerHiscoreTable.tsx
- src/components/molecules/PlayerLookup/PlayerLookup.styled.ts
- src/helpers/hiscores/hiscoresUtils.ts
- src/helpers/router.ts
- src/hooks/useHiscores.ts
- src/pages/hiscores/index.tsx
- src/pages/hiscores/player/[accountName].tsx
- Implemented pagination and scroll to top controls for Hiscores
- Implemented query strings for current skill and hiscore page so hiscore pages can be deep linked
- Added skill links to player hiscore table for easier navigation
- Fixed issue with some player hiscore table ranks being incorrect due to accounts with baseline exp being factored into the rank
- Added `isNotBaselineExp` helper which is used by both hiscore tables now
- Fixed some minor spacing issues with PlayerLookup
- Minor refactoring
> F2P-83 | Potentially add Pagination to Hiscores if the need arises

- src/components/organisms/PasswordModal/PasswordModal.tsx
- src/helpers/string/stringUtils.ts
- src/pages/account/game-accounts/create/index.tsx
- Swapped out password validation for password fixing so users can have special characters in their game account passwords
- Enforced game account password max length to be 20 since the game client does not let you type in more than that amount
> F2P-72 | We should allow special characters in game account passwords but replace with underscore like RSC does

- src/styledPages/ReportABug.styled.ts
- Fixed Bug Type dropdown default selected item background color by increasing specificity of `.Mui-selected` selector
> F2P-117 | Bug Type dropdown color issue

- src/components/atoms/MainNavigation/MainNavigation.styled.ts
- src/components/molecules/ReadMore/ReadMore.tsx
- src/theme/styles.css
- Changed global link color to `green`
- Removed non-breakable space before the Read More link
- Renamed `Read More` to `Read post >>`
- Changed some `#800080` hex references to `purple` to be consistent since they are the same value
> F2P-112 | Read More links look bad again

- src/hooks/useHiscores.ts
- Fixed issue in Overall hiscores where if two players have the same total, it was not showing the player with the most experience as the highest rank of those players
https://github.com/aldrichdev/neatf2p-nextjs/issues/80
> F2P-119 | If two players on hiscores have same level, the player with more EXP should get the higher rank

- src/helpers/hiscores/hiscoresUtils.ts
- src/hooks/useHiscores.ts
- src/pages/hiscores/player/[accountName].tsx
- Fixed issue with Player Hiscores where some ranks were incorrect if multiple players had the same experience in a skill, by moving `compareHiscores` function to `hiscoresUtils` and reusing this function for both the main hiscores and player hiscores, and also filtering the hiscores on the player page before sorting
> F2P-111 | Player hiscore ranks still incorrect sometimes if EXP is same for multiple players

- src/pages/api/updateGameAccountPassword/index.ts
- src/pages/api/updateGameAccountUsername/index.ts
- src/pages/api/updateWebsiteUserEmailAddress/index.ts
- Fixed flaws with `updateGameAccountXXX` APIs by checking that the `websiteUserId` matches the current `userId` - this prevents users from updating accounts that aren't theirs
- Fixed `updateGameAccountUsername` so it does not update the username if the new username already exists (i.e. someone else has it) or if the `former_name` has a value (indicates the user already renamed, so this prevents users from renaming multiple times via the API)
- Fixed a  bug with `updateWebsiteUserEmailAddress` where it did not check if the new email already existed in the DB
> F2P-124 | API Security Flaws

- src/pages/account/create/index.tsx
- src/pages/account/login/index.tsx
- Disabled Log In / Submit buttons after click on Login and Create pages for website accounts so the APIs tied to these buttons are not called multiple times due to the button being clicked more than once
Not actually 100% sure if this will fix the issue. The issue isn't really reproducible locally with this fix though.
> F2P-136 | APIs fail with 403 sometimes

- src/helpers/api/apiHandler.ts
- src/helpers/api/apiUtils.ts
- src/helpers/db.ts
- src/pages/account/game-accounts/create/index.tsx
- src/pages/api/createPlayerRecord/index.ts
- Prevent `createPlayerRecord` from adding new game accounts under different website users
- Moved input validation to API so Postman/cURL requests are validated for new accounts
- Fixed rows affected error reporting in `handleManipulate`
- Created `sendBadRequest` helper
> F2P-134 | A couple `createPlayerRecord` issues remaining

- src/components/organisms/GameAccountsTable/GameAccountsTable.styled.ts
- src/components/organisms/GameAccountsTable/GameAccountsTable.tsx
- src/components/organisms/GameAccountsTableMobile/GameAccountsTableMobile.styled.ts
- src/components/organisms/GameAccountsTableMobile/GameAccountsTableMobile.tsx
- src/components/organisms/PasswordModal/PasswordModal.tsx
- src/components/organisms/RenameAccountModal/RenameAccountModal.tsx
- src/helpers/api/apiUtils.ts
- src/hooks/useGameAccounts.ts
- src/pages/account/change-email/[id].tsx
- src/pages/account/change-password/index.tsx
- src/pages/account/change-username/index.tsx
- src/pages/account/game-accounts/create/index.tsx
- src/pages/account/session-expired/index.tsx
- src/pages/admin/newsPostForm/index.tsx
- src/pages/api/createPlayerSkillRecords/index.ts
- src/pages/api/getGameAccountsForUser/index.ts
- src/pages/api/submitNewsPost/index.ts
- src/pages/api/updateGameAccountPassword/index.ts
- src/pages/api/updateGameAccountUsername/index.ts
- src/pages/api/updateWebsiteUserEmailAddress/index.ts
- src/pages/api/updateWebsiteUserPassword/index.ts
- src/pages/api/updateWebsiteUserUsername/index.ts
- Added Session Expired page and functionality to redirect to this page when a 403 is encountered and the user is stuck on the page
- Fixed duplicate loading spinners on the game accounts page
This isn't a fix for the 403 error completely, because I realized it's not possible to do so. This 403 issue occurs when you log into your account in a different browser or computer, or even a different website (i.e. you develop locally like me). So a 403 is sort of an _expected_ scenario because you logged in elsewhere and your session cookie is no longer valid.
> F2P-136 | Spinning 403 issue solve

- src/globalTypes/Database/PlayerDataRow.ts
- src/pages/api/getGameAccountsForUser/index.ts
- Removed pass and salt columns from `getGameAccountsForUser` query as the website was doing nothing with them
Confirmed password update feature still functions correctly and that the game accounts page still works normally.
> F2P-147 | Remove unused `pass` and `salt` fields

- src/helpers/api/apiUtils.ts
- src/pages/api/submitNewsPost/index.ts
- Added code to prevent any authenticated user from submitting news posts by checking if they are an admin in the query
- Added function comment to `shouldBlockApiCall` explaining what it does
Tested the `submitNewsPost` API endpoint in Postman:
- With session cookie and user ID of admin user specified in the request, the news post is created.
- With session cookie and user ID of a non-admin user specified, `Error: Unauthorized` is returned.
- If the `userId` provided is an admin user but the session cookie does not match the `session` of this `userId`, the request will be blocked (existing functionality) with the error `Forbidden`.
> F2P-137 | What can we do to protect submitNewsPost calls?

- src/components/atoms/BodyText/BodyText.tsx
- src/components/molecules/CharacterInfoModal/CharacterInfoModal.styled.tsx
- src/components/molecules/CharacterInfoModal/CharacterInfoModal.tsx
- src/helpers/string/stringUtils.ts
- Fixed KDR calculation error if deaths are 0
- Fixed issue with `BodyText` properties not working in some modals
- Refactored some of the KDR code
- KDR calculations work as expected now.
- Password and rename modal body text is aligned and spaced correctly now.
> F2P-148 | KDR and `BodyText` fixes

- src/pages/api/getPlayerHiscore/index.ts
- src/pages/api/queryHiscores/index.ts
- Updated hiscores queries to return data for normal players only
- Mods and admins do not show in hiscores and cannot be looked up
> F2P-162 | Need to hide mods from hiscores

- src/components/organisms/RenameAccountModal/RenameAccountModal.tsx
- src/globalTypes/AxiosErrorResponse.ts
- src/helpers/api/apiHandler.ts
- src/helpers/api/apiUtils.ts
- src/pages/api/updateGameAccountUsername/index.ts
- Made changes to rename logic so players can rename their account to the same name but with a different case
- Removed some unnecessary `.toString()` and `${}` code
https://github.com/aldrichdev/neatf2p-nextjs/issues/107
- Code works as intended, I can rename to an uppercase, lowercase, or mixed case of the same name.
- I cannot rename to a different case of a completely different name
> F2P-164 | Users cannot rename to lowercase or uppercase

- src/components/organisms/PasswordModal/PasswordModal.tsx
- src/components/organisms/RenameAccountModal/RenameAccountModal.tsx
- src/helpers/api/apiUtils.ts
- src/hooks/useGameAccounts.ts
- src/pages/account/change-email/[id].tsx
- src/pages/account/change-password/index.tsx
- src/pages/account/change-username/index.tsx
- src/pages/account/game-accounts/create/index.tsx
- src/pages/admin/newsPostForm/index.tsx
- src/pages/api/updateGameAccountUsername/index.ts
- Fixed issue with account renames not working
- Fixed typing of API errors in FE by changing all error types to `AxiosError<string>`
- Fixed issue in `handleForbiddenRedirect` due to the `error` parameter being the wrong type
Made sure account renames work now on the website, and renaming to the same name but in a different case still works.
> Account rename bug fix

- src/pages/account/login/index.tsx
- Fixed issue with website accounts not being able to log in if their email address has a plus sign (or any other odd character)
- Confirmed I can log in with an email address `my+email@gmail.com` with no errors or warnings. Other email addresses without special characters still work fine and can login.
> F2P-142 | Plus signs in email addresses ➡ users cannot login

- src/components/molecules/Modal/Modal.styled.ts
- src/components/molecules/Modal/Modal.tsx
- src/components/molecules/Modal/Modal.types.ts
- src/pages/admin/newsPostForm/index.tsx
- Made news post form preview modal scrollable so the entire body can be read
- Removed unnecessary code and `TODO`. (This may cause the content shift in the game accounts table to be a bit more pronounced when opening a modal than it was before, but it was a half-effective solution anyway, and will be fully addressed in `F2P-58`)
- Preview modal is now less tall and has a scrollable body.
- Other modals are unaffected except for a slight change to the `top` % for the absolutely positioned modal. It does not look bad.
> F2P-133 | News post preview modal doesn't handle long posts well

- src/components/MainNavigationDropdownItem/MainNavigationDropdownItem.styled.ts
- src/components/atoms/MainNavigation/MainNavigation.styled.ts
- src/styledPages/App.styled.ts
- Moved navigation closer to header image
- Fixed mobile view of navigation
It was decided not to make the header image fade down, as what I implemented here looked better.
> F2P-172 | Make header image fade down

- src/pages/account/create/index.tsx
- src/pages/api/createUserAccount/index.ts
- Fixed error message when visitors try to create new website accounts
- Users that try to create a new website account with an email or username that is already taken are presented with a more meaningful and clear error message
- Users can still create new website accounts
> F2P-160 | Error on account creation needs tweaking

- src/components/MainNavigationDropdownItem/MainNavigationDropdownItem.styled.ts
- src/components/MainNavigationDropdownItem/MainNavigationDropdownItem.tsx
- src/components/atoms/MainNavigation/MainNavigation.styled.ts
- src/theme/styles.css
- Fixed issue in news post form preview where bullets weren't showing for lists
- Removed default CSS for `ul` element from `styles.css`
- Updated other places where `ul` elements are used to remove padding and default bullet
- Confirmed bullets appear in the preview modal now
- Confirmed main navigation, about page info section and hiscores menu item list all look good
> F2P-175 | Lists in news post preview modal not appearing correctly

- src/pages/how-to-play/index.tsx
- src/styledPages/HowToPlay.styled.ts
- Added notice to How to Play that you can't create a game account via the game clients
- Marked RSC+ as the recommended client
- Added a large warning at the top of the page that says, you need to create an account first.
- Added text to mention that there isn’t a way to play on mobile right now.
> F2P-184, F2P-178 | How to Play page changes

- src/pages/api/updateGameAccountUsername/index.ts
- Fixed issue with users being able to rename their game accounts to the same name but different casing of another user
- Kept functionality that allows users to rename their accounts to a different casing of the same name, by adding an ID check
> F2P-209 | Account rename -  Existing username should should be insensitive
